### ISSUE TITLE
Implement method "executeJavascript(...)"

### ISSUE THREAD

**Issue by ShelleyLake** [winsoft666/QCefView#1]
@winsoft666 
First of all thanks for your beautiful example.
It is the first working implementation I see that is able to render web contents to a QWidget that is hidden (i.e has no visible parent) and save it to a QImage or so.

May I suggest you to implement the executeJavascript() method ? :-)

```
void QCefViewImplement::executeJavascript(const QString& javascript) const
{
  CefString strJavascript;
  strJavascript.FromString(javascript.toStdString());

  if (pQCefViewHandler_ && pQCefViewHandler_->GetBrowser() && pQCefViewHandler_->GetBrowser()->GetMainFrame())
    pQCefViewHandler_->GetBrowser()->GetMainFrame()->ExecuteJavaScript(strJavascript, pQCefViewHandler_->GetBrowser()->GetMainFrame()->GetURL(), 0);
}

```
See https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration

**Comment by winsoft666** [comment]
thanks for your suggest, you are a good man and  I will add `executeJavascript` to next release.
